# Generated by Django 5.2.7 on 2025-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
