# Generated by Django 5.2.7 on 2025-10-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
