# Generated by Django 5.2.7 on 2025-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
